import type { Metadata } from 'next';
import { i18nConfig } from '../../../i18nConfig';
import '@/globals.scss';
import Header from '@/components/Header/Header';
import Footer from '@/components/Footer/Footer';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { dir } from 'i18next';
import { AppThemeProvider } from '@/theme/AppThemeProvider';
import ErrorBoundary from '@/components/ErrorBoundary/ErrorBoundary';

export function generateStaticParams() {
    return i18nConfig.locales.map((locale) => ({ locale }));
}

export const metadata: Metadata = {
    title: 'REST/GraphQL Client',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
    params: { locale },
}: Readonly<{
    children: React.ReactNode;
    params: { locale: string };
}>) {
    return (
        <html lang={locale} dir={dir(locale)}>
            <body>
                <AppRouterCacheProvider>
                    <AppThemeProvider>
                        <Header />
                        <ErrorBoundary>{children}</ErrorBoundary>
                        <Footer />
                    </AppThemeProvider>
                </AppRouterCacheProvider>
            </body>
        </html>
    );
}
