import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { i18nConfig } from '../../../i18nConfig';
import './../globals.scss';
import Header from '@/components/Header/Header';
import Footer from '@/components/Footer/Footer';

const inter = Inter({ subsets: ['latin'] });

export function generateStaticParams() {
    return i18nConfig.locales.map((locale) => ({ locale }));
}

export const metadata: Metadata = {
    title: 'REST/GraphQL Client',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    );
}
